# Generated by Django 2.2.13 on 2021-01-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
